name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies API
        run: npm install --prefix services/api

      - name: Run tests
        run: npm --prefix services/api test

      - name: Install dependencies Web
        run: npm install --prefix apps/web

      - name: Build web app
        run: npm --prefix apps/web run build
